<?php
// privacy-policy.php - Complete Official Privacy Policy & Data Protection
require_once __DIR__ . '/config/app.php';

$pageTitle = "Privacy Policy - My Advocate";
$pageDescription = "Official Privacy Policy of My Advocate explaining how we collect, safeguard, and manage user and advocate data under the IT Act and data protection regulations.";

require_once INCLUDES_PATH . '/header.php';
?>

<div class="container" style="padding-top: 2rem; padding-bottom: 4rem;">
    <!-- Breadcrumbs -->
    <nav style="font-size: 0.8125rem; color: var(--text-muted); margin-bottom: 1.25rem;">
        <a href="./">Home</a> &bull; <span>Legal & Compliance</span> &bull; <span>Privacy Policy</span>
    </nav>

    <div style="max-width: 900px; margin: 0 auto;">
        <!-- Legal Switcher Tabs -->
        <div class="legal-tabs" style="display: flex; gap: 0.5rem; margin-bottom: 1.5rem; overflow-x: auto; padding-bottom: 4px;">
            <a href="disclaimer" class="btn btn-outline btn-sm">
                <i class="fas fa-gavel"></i> BCI Disclaimer
            </a>
            <a href="privacy" class="btn btn-primary btn-sm">
                <i class="fas fa-user-shield"></i> Privacy Policy
            </a>
            <a href="terms" class="btn btn-outline btn-sm">
                <i class="fas fa-file-contract"></i> Terms and Conditions
            </a>
        </div>

        <div class="stat-box" style="padding: 2.5rem 2rem; border-top: 4px solid var(--brand-red);">
            <div style="display: flex; justify-content: space-between; align-items: flex-start; flex-wrap: wrap; gap: 1rem; margin-bottom: 1.5rem;">
                <div>
                    <span class="badge-verification badge-verified" style="margin-bottom: 0.5rem;">
                        <i class="fas fa-shield-halved"></i> Data Protection & Privacy
                    </span>
                    <h1 style="font-size: 2rem; color: var(--primary); margin-top: 0.25rem;">
                        Privacy Policy
                    </h1>
                </div>
                <div style="font-size: 0.8125rem; color: var(--text-muted); background: var(--bg-alt); padding: 0.4rem 0.75rem; border-radius: var(--radius-sm); border: 1px solid var(--border-color); font-weight: 600;">
                    <i class="fas fa-calendar-check" style="color: var(--brand-gold);"></i> Last Update : 02 Oct 2026
                </div>
            </div>

            <p style="color: var(--text-muted); font-size: 0.875rem; margin-bottom: 1.75rem;">
                Effective from: 02 Oct 2026
            </p>

            <div style="line-height: 1.8; color: var(--text-main); font-size: 0.9375rem; display: flex; flex-direction: column; gap: 1.75rem;">
                <!-- 1. Introduction -->
                <div>
                    <h3 style="font-size: 1.15rem; color: var(--primary); margin-bottom: 0.5rem;">1. Introduction</h3>
                    <p style="margin-bottom: 0.75rem;">
                        Welcome to <strong>My Advocate (perviously MyAdv India)</strong>, an initiative by <strong>OfferPlant Technologies Private Limited</strong> (“Company”, “us”, “we”, or “our”). We operate <strong>https://myadv.in</strong> (hereinafter referred to as <strong>“Service”</strong>).
                    </p>
                    <p style="margin-bottom: 0.75rem;">
                        Our Privacy Policy governs your visit to <strong>https://myadv.in</strong>, and explains how we collect, safeguard, and disclose information resulting from your use of our Service.
                    </p>
                    <p>
                        We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used have the same meanings as in our Terms and Conditions.
                    </p>
                </div>

                <!-- 2. Definitions -->
                <div>
                    <h3 style="font-size: 1.15rem; color: var(--primary); margin-bottom: 0.5rem;">2. Definitions</h3>
                    <ul style="padding-left: 1.25rem; display: flex; flex-direction: column; gap: 0.5rem;">
                        <li><strong>SERVICE:</strong> The https://myadv.in website operated by My Advocate (perviously MyAdv India) | OfferPlant Technologies Private Limited.</li>
                        <li><strong>PERSONAL DATA:</strong> Data about a living individual who can be identified from that data (or from those and other information either in our possession or likely to come into our possession).</li>
                        <li><strong>USAGE DATA:</strong> Data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</li>
                        <li><strong>COOKIES:</strong> Small files stored on your device (computer or mobile device).</li>
                        <li><strong>DATA CONTROLLER:</strong> A natural or legal person who determines the purposes for which and the manner in which personal data are processed.</li>
                        <li><strong>DATA PROCESSORS (OR SERVICE PROVIDERS):</strong> Any natural or legal person who processes data on behalf of the Data Controller.</li>
                        <li><strong>DATA SUBJECT / THE USER:</strong> The individual using our Service who is the subject of Personal Data.</li>
                    </ul>
                </div>

                <!-- 3. Information Collection and Use -->
                <div>
                    <h3 style="font-size: 1.15rem; color: var(--primary); margin-bottom: 0.5rem;">3. Information Collection and Use</h3>
                    <p>
                        We collect several different types of information for various purposes to provide, secure, and continuously improve our Service to you.
                    </p>
                </div>

                <!-- 4. Types of Data Collected -->
                <div>
                    <h3 style="font-size: 1.15rem; color: var(--primary); margin-bottom: 0.5rem;">4. Types of Data Collected</h3>
                    
                    <h4 style="font-size: 1rem; color: var(--primary); margin: 0.75rem 0 0.35rem;">A. Personal Data</h4>
                    <p style="margin-bottom: 0.5rem;">While using our Service, we may ask you to provide us with certain personally identifiable information:</p>
                    <ul style="padding-left: 1.25rem; margin-bottom: 1rem;">
                        <li>Email address</li>
                        <li>First name, last name, and advocate titles</li>
                        <li>Phone / Mobile number</li>
                        <li>Bar Council Enrollment Number and Enrollment Year</li>
                        <li>Address, State, District, City, and PIN code</li>
                        <li>Court jurisdictions, Bar Association memberships, and practice areas</li>
                        <li>Photographs, credentials, and verification documentation</li>
                        <li>Cookies and Usage Data</li>
                    </ul>

                    <h4 style="font-size: 1rem; color: var(--primary); margin: 0.75rem 0 0.35rem;">B. Advocate Contact Privacy Controls</h4>
                    <p style="margin-bottom: 0.5rem;">
                        Practicing advocates registered or claimed on our platform can configure their contact visibility settings anytime via their dashboard:
                    </p>
                    <ul style="padding-left: 1.25rem; margin-bottom: 1rem;">
                        <li><strong>Public:</strong> Contact details are displayed directly on the public directory.</li>
                        <li><strong>Masked / Registered Only:</strong> Details are hidden from casual crawlers and accessible only to registered members.</li>
                        <li><strong>Private:</strong> Contact details remain strictly confidential and hidden from public display.</li>
                    </ul>

                    <h4 style="font-size: 1rem; color: var(--primary); margin: 0.75rem 0 0.35rem;">C. Usage & Diagnostic Data</h4>
                    <p style="margin-bottom: 1rem;">
                        We collect information sent by your browser whenever you visit our Service (e.g. IP address, browser type, pages visited, timestamps, device identifiers, and operating system).
                    </p>

                    <h4 style="font-size: 1rem; color: var(--primary); margin: 0.75rem 0 0.35rem;">D. Tracking & Cookies Data</h4>
                    <p>
                        We use session cookies, preference cookies, security cookies, and analytics cookies to operate our portal efficiently and maintain session security.
                    </p>
                </div>

                <!-- 5. Use of Data -->
                <div>
                    <h3 style="font-size: 1.15rem; color: var(--primary); margin-bottom: 0.5rem;">5. Use of Data</h3>
                    <p style="margin-bottom: 0.5rem;">My Advocate (perviously MyAdv India) uses collected data for the following purposes:</p>
                    <ul style="padding-left: 1.25rem;">
                        <li>To provide, maintain, and secure our legal directory and repository services.</li>
                        <li>To notify you about changes, updates, or statutory notifications.</li>
                        <li>To verify advocate credentials and manage account authentication.</li>
                        <li>To provide responsive customer and grievance support.</li>
                        <li>To detect, prevent, and mitigate security threats, fraud, or misuse.</li>
                        <li>To fulfill our obligations and enforce our terms and contracts.</li>
                    </ul>
                </div>

                <!-- 6. Retention & Security of Data -->
                <div>
                    <h3 style="font-size: 1.15rem; color: var(--primary); margin-bottom: 0.5rem;">6. Retention & Security of Data</h3>
                    <p style="margin-bottom: 0.75rem;">
                        We retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy and to comply with statutory legal obligations under Indian law.
                    </p>
                    <p>
                        The security of your data is paramount to us. We implement standard encryption (SSL/TLS), strict database permissions, and routine audits. However, please note that no method of electronic storage or transmission over the Internet is 100% impenetrable.
                    </p>
                </div>

                <!-- 7. Disclosure of Data -->
                <div>
                    <h3 style="font-size: 1.15rem; color: var(--primary); margin-bottom: 0.5rem;">7. Disclosure of Data</h3>
                    <p style="margin-bottom: 0.5rem;">We may disclose personal information in good faith when necessary:</p>
                    <ul style="padding-left: 1.25rem;">
                        <li>To comply with a legal obligation, court order, or governmental request.</li>
                        <li>To protect and defend the rights or property of OfferPlant Technologies Private Limited.</li>
                        <li>To prevent or investigate possible wrongdoing in connection with the Service.</li>
                        <li>To protect the personal safety of users or the public.</li>
                    </ul>
                </div>

                <!-- 8. Links to Other Sites -->
                <div>
                    <h3 style="font-size: 1.15rem; color: var(--primary); margin-bottom: 0.5rem;">8. Links to Other Sites</h3>
                    <p>
                        Our Service may contain links to government portals, court websites, or Bar Council registries. We strongly advise you to review the Privacy Policy of every external site you visit, as we have no control over their practices.
                    </p>
                </div>

                <!-- 9. Contact Us -->
                <div style="background: #f8fafc; padding: 1.25rem 1.5rem; border-radius: var(--radius-sm); border: 1px solid var(--border-color);">
                    <h3 style="font-size: 1.15rem; color: var(--primary); margin-bottom: 0.5rem;">
                        9. Grievance Officer & Contact
                    </h3>
                    <p style="margin-bottom: 0.5rem;">
                        If you have questions about this Privacy Policy, wish to exercise data rights, or request rectification:
                    </p>
                    <p style="margin-bottom: 0;">
                        <strong>Grievance Officer:</strong> OfferPlant Technologies Private Limited &bull; 
                        <strong>Email:</strong> <a href="mailto:help@myadv.in">help@myadv.in</a> &bull; 
                        <strong>Portal:</strong> <a href="contact">Contact & Grievance Desk</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<?php require_once INCLUDES_PATH . '/footer.php'; ?>
